

CREATE TABLE IF NOT EXISTS common_player_info (
    person_id INT PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    display_first_last TEXT,
    display_last_comma_first TEXT,
    display_fi_last TEXT,
    player_slug TEXT,
    birthdate DATE, 
    school TEXT,
    country TEXT,
    last_affiliation TEXT,
    height INTEGER,
    weight INTEGER,
    season_exp INTEGER,
    jersey INTEGER,
    position TEXT,
    rosterstatus TEXT,
    games_played_current_season_flag TEXT,
    team_id INTEGER,
    team_name TEXT,
    team_abbreviation TEXT,
    team_code TEXT,
    team_city TEXT,
    playercode TEXT,
    from_year DATE,
    to_year DATE,
    dleague_flag TEXT,
    nba_flag TEXT,
    games_played_flag TEXT,
    draft_year TEXT,
    draft_round TEXT,
    draft_number TEXT,
    greatest_75_flag TEXT
);

CREATE TABLE IF NOT EXISTS draft_combine_stats (
    season DATE,
    player_id INTEGER,
    first_name TEXT,
    last_name TEXT,
    player_name TEXT,
    position TEXT,
    height_wo_shoes FLOAT,
    height_wo_shoes_ft_in FLOAT,
    height_w_shoes FLOAT,
    height_w_shoes_ft_in FLOAT,
    weight FLOAT,
    wingspan FLOAT,
    wingspan_ft_in FLOAT,
    standing_reach FLOAT,
    standing_reach_ft_in FLOAT,
    body_fat_pct FLOAT,
    hand_length FLOAT,
    hand_width FLOAT,
    standing_vertical_leap FLOAT,
    max_vertical_leap FLOAT,
    lane_agility_time FLOAT,
    modified_lane_agility_time FLOAT,
    three_quarter_sprint FLOAT,
    bench_press FLOAT,
    spot_fifteen_corner_left TEXT,
    spot_fifteen_break_left TEXT,
    spot_fifteen_top_key TEXT,
    spot_fifteen_break_right TEXT,
    spot_fifteen_corner_right TEXT,
    spot_college_corner_left TEXT,
    spot_college_break_left TEXT,
    spot_college_top_key TEXT,
    spot_college_break_right TEXT,
    spot_college_corner_right TEXT,
    spot_nba_corner_left TEXT,
    spot_nba_break_left TEXT,
    spot_nba_top_key TEXT,
    spot_nba_break_right TEXT,
    spot_nba_corner_right TEXT,
    off_drib_fifteen_break_left TEXT,
    off_drib_fifteen_top_key TEXT,
    off_drib_fifteen_break_right TEXT,
    off_drib_college_break_left TEXT,
    off_drib_college_top_key TEXT,
    off_drib_college_break_right TEXT,
    on_move_fifteen TEXT,
    on_move_college TEXT
);


CREATE TABLE IF NOT EXISTS draft_history (
    person_id              INT,
    player_name            TEXT,
    season                 DATE,
    round_number           INT,
    round_pick             INT,
    overall_pick           INT,
    draft_type             TEXT,
    team_id                INT,
    team_city              TEXT,
    team_name              TEXT,
    team_abbreviation      TEXT,
    organization           TEXT,
    organization_type      TEXT,
    player_profile_flag    INT
);


CREATE TABLE IF NOT EXISTS game (
    season_id                  INT,
    team_id_home               INT,
    team_abbreviation_home     TEXT,
    team_name_home             TEXT,
    game_id                    INT PRIMARY KEY,
    game_date                  DATE,
    matchup_home               TEXT,
    wl_home                    TEXT,
    min                        INT,
    fgm_home                   FLOAT,
    fga_home                   FLOAT,
    fg_pct_home                FLOAT,
    fg3m_home                  FLOAT,
    fg3a_home                  FLOAT,
    fg3_pct_home               FLOAT,
    ftm_home                   FLOAT,
    fta_home                   FLOAT,
    ft_pct_home                FLOAT,
    oreb_home                  FLOAT,
    dreb_home                  FLOAT,
    reb_home                   FLOAT,
    ast_home                   FLOAT,
    stl_home                   FLOAT,
    blk_home                   FLOAT,
    tov_home                   FLOAT,
    pf_home                    FLOAT,
    pts_home                   FLOAT,
    plus_minus_home            INT,
    video_available_home       INT,
    team_id_away               INT,
    team_abbreviation_away     TEXT,
    team_name_away             TEXT,
    matchup_away               TEXT,
    wl_away                    TEXT,
    fgm_away                   FLOAT,
    fga_away                   FLOAT,
    fg_pct_away                FLOAT,
    fg3m_away                  FLOAT,
    fg3a_away                  FLOAT,
    fg3_pct_away               FLOAT,
    ftm_away                   FLOAT,
    fta_away                   FLOAT,
    ft_pct_away                FLOAT,
    oreb_away                  FLOAT,
    dreb_away                  FLOAT,
    reb_away                   FLOAT,
    ast_away                   FLOAT,
    stl_away                   FLOAT,
    blk_away                   FLOAT,
    tov_away                   FLOAT,
    pf_away                    FLOAT,
    pts_away                   FLOAT,
    plus_minus_away            INT,
    video_available_away       INT,
    season_type                TEXT
);

CREATE TABLE IF NOT EXISTS game_info (
    game_id       INT PRIMARY KEY,
    game_date     DATE,
    attendance    FLOAT,
    game_time     TIME
);

CREATE TABLE IF NOT EXISTS game_summary (
    game_id                            INT PRIMARY KEY,
    game_date_est                      DATE,
    game_sequence                      FLOAT,
    game_status_id                     INT,
    game_status_text                   TEXT,
    gamecode                           TEXT,
    home_team_id                       INT,
    visitor_team_id                    INT,
    season                             DATE,
    live_period                        INT,
    live_pc_time                       TEXT,
    natl_tv_broadcaster_abbreviation   TEXT,
    live_period_time_bcast             TEXT,
    wh_status                          INT
);

CREATE TABLE IF NOT EXISTS inactive_players (
    game_id             INT,
    player_id           INT,
    first_name          TEXT,
    last_name           TEXT,
    jersey_num          INT,
    team_id             INT,
    team_city           TEXT,
    team_name           TEXT,
    team_abbreviation   TEXT
);


CREATE TABLE line_score (
    game_date_est DATE,
    game_sequence FLOAT,
    game_id INT,
    team_id_home INT,
    team_abbreviation_home TEXT,
    team_city_name_home TEXT,
    team_nickname_home TEXT,
    team_wins_losses_home TEXT,
    pts_qtr1_home FLOAT,
    pts_qtr2_home INT,
    pts_qtr3_home INT,
    pts_qtr4_home INT,
    pts_ot1_home FLOAT,
    pts_ot2_home FLOAT,
    pts_ot3_home FLOAT,
    pts_ot4_home FLOAT,
    pts_ot5_home FLOAT,
    pts_ot6_home FLOAT,
    pts_ot7_home FLOAT,
    pts_ot8_home FLOAT,
    pts_ot9_home FLOAT,
    pts_ot10_home FLOAT,
    pts_home FLOAT,
    team_id_away INT,
    team_abbreviation_away TEXT,
    team_city_name_away TEXT,
    team_nickname_away FLOAT,
    team_wins_losses_away TEXT,
    pts_qtr1_away FLOAT,
    pts_qtr2_away INT,
    pts_qtr3_away INT,
    pts_qtr4_away FLOAT,
    pts_ot1_away FLOAT,
    pts_ot2_away FLOAT,
    pts_ot3_away FLOAT,
    pts_ot4_away FLOAT,
    pts_ot5_away FLOAT,
    pts_ot6_away FLOAT,
    pts_ot7_away FLOAT,
    pts_ot8_away FLOAT,
    pts_ot9_away FLOAT,
    pts_ot10_away FLOAT,
    pts_away FLOAT
);


CREATE TABLE officials (
    game_id INT,
    official_id INT,
    first_name TEXT,
    last_name TEXT,
    jersey_num INT
);


CREATE TABLE other_stats (
    game_id INT,
    league_id INT,
    team_id_home INT,
    team_abbreviation_home TEXT,
    team_city_home TEXT,
    pts_paint_home INT,
    pts_2nd_chance_home INT,
    pts_fb_home INT,
    largest_lead_home INT,
    lead_changes INT,
    times_tied INT,
    team_turnovers_home FLOAT,
    total_turnovers_home FLOAT,
    team_rebounds_home FLOAT,
    pts_off_to_home FLOAT,
    team_id_away INT,
    team_abbreviation_away TEXT,
    team_city_away TEXT,
    pts_paint_away INT,
    pts_2nd_chance_away INT,
    pts_fb_away INT,
    largest_lead_away INT,
    team_turnovers_away FLOAT,
    total_turnovers_away FLOAT,
    team_rebounds_away FLOAT,
    pts_off_to_away FLOAT
);

CREATE TABLE play_by_play (
    game_id INT,
    eventnum INT,
    eventmsgtype INT,
    eventmsgactiontype INT,
    period INT,
    wctimestring TIME,
    pctimestring TIME,
    homedescription TEXT,
    neutraldescription TEXT,
    visitordescription TEXT,
    score TEXT,
    scoremargin INT,
    person1type INT,
    player1_id  INT,
    player1_name TEXT,
    player1_team_id FLOAT,
    player1_team_city TEXT,
    player1_team_nickname TEXT,
    player1_team_abbreviation TEXT,
    person2type INT,
    player2_id INT,
    player2_name TEXT,
    player2_team_id INT,
    player2_team_city TEXT,
    player2_team_nickname TEXT,
    player2_team_abbreviation TEXT,
    person3type INT,
    player3_id INT,
    player3_name TEXT,
    player3_team_id INT,
    player3_team_city TEXT,
    player3_team_nickname TEXT,
    player3_team_abbreviation TEXT,
    video_available_flag INT
);

CREATE TABLE player (
    id INT PRIMARY KEY,
    full_name TEXT,
    first_name TEXT,
    last_name TEXT,
    is_active INT
);

CREATE TABLE team (
    id INT PRIMARY KEY,
    full_name TEXT,
    abbreviation TEXT,
    nickname TEXT,
    city TEXT,
    state TEXT,
    year_founded DATE
);


CREATE TABLE team_details (
    team_id INT PRIMARY KEY,
    abbreviation TEXT,
    nickname TEXT,
    yearfounded DATE,
    city TEXT,
    arena TEXT,
    arenacapacity INT,
    owner TEXT,
    generalmanager TEXT,
    headcoach TEXT,
    dleagueaffiliation TEXT,
    facebook TEXT,
    instagram TEXT,
    twitter TEXT
);

CREATE TABLE team_history (
    team_id INT PRIMARY KEY,             
    city TEXT,                            
    nickname TEXT,                       
    year_founded INT,                     
    year_active_till INT                 
);
